FROM node:20

WORKDIR /opt/backend

COPY package.json .
RUN npm install

COPY *.js .

# ENV DB_HOST="mysql"
ENV DB_HOST="localhost"
CMD ["node", "index.js"]


RUN apt-get update && apt-get install -y telnetd
